; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define ApplicationName "nr-tool-data"
; Version value can be set by argument in cmd line, if you wish to run script directly from GUI, then please specify version number by manually
#define ApplicationVersion "1.0.2"
#define ApplicationPublisher "KazNU"
#define SetupExeName "nr_tool_data_setup"
#define ControlpanelName "KazNRDC nuclear data library"

[Setup]
AppId={{dddb3e46-f2e9-43ed-89c3-b089ce05cee4}
AppName={#ApplicationName}
AppVersion={#ApplicationVersion}
AppPublisher={#ApplicationPublisher}
DefaultDirName={localappdata}\{#ApplicationName}
DisableProgramGroupPage=yes
DisableWelcomePage=no
WizardImageFile=AppLogo-Large.bmp
WizardSmallImageFile=AppLogo-Small.bmp
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=..\output\installer
OutputBaseFilename={#SetupExeName}_v{#ApplicationVersion}
UninstallDisplayName = {#ControlpanelName}
UninstallDisplayIcon={app}\App.ico
UninstallIconFile={app}\App.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UsePreviousTasks=no
UsePreviousAppDir=no

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\nr-tool-data\ENDFB-VIII\decay\*.endf"; DestDir: "{localappdata}\KazNRDC\xsdir\ENDFB-VIII\decay"; Flags: ignoreversion 
Source: "..\nr-tool-data\ENDFB-VIII\neutron\*.endf"; DestDir: "{localappdata}\KazNRDC\xsdir\ENDFB-VIII\neutron"; Flags: ignoreversion 